### ISSUE TITLE
Hello  Bre3n!  The  avatars of players is not displayed in the obs,if there is something wrong with it

### ISSUE THREAD

**Issue by bohecsgo** [Bre3n/Custom-CSGO-HUD#5]
Hello  Bre3n!  The  avatars of players is not displayed in the obs,if there is something wrong with it in reworked hud. Could u  add the codes into the  resource, cuz I can`t find the html to add the codes.

**Comment by Bre3n** [comment]
Hi. Yeah, I know, I deleted the HUD avatars because I didn't want somebody to create an inappropriate avatar. What HUD are you using? PL or EN? If you want, I can add avatars to any of the versions in my free time, or if you want to do it on your own. HUDs are in a public/huds folder and simply compare default and reworked version and do what you want.

**Comment by bohecsgo** [comment]
So grateful to u  replying to me!
I am a beginner , I  think I would get a  bad result.  Then I still need your help once again.I will extremely  appreciate that you can help to add the codes to the reworked EN in your free time.Also,I will have a try firstly.
